//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------

mesh
{
	file : inductor.msh ;
	unit : m ;
}

solver
{
	linear
	{
		library : mumps ;
	}

	nonlinear
	{
		tolerance      : 1e-8 ;
		max iterations : 100 ;
		algorithm      : Newton ;
	}

	timestep
	{
		initial timestep : 0.01 ms ;
		maximum timestep : 0.2 ms ;
		simulation time  : 80 ms ;
		adapt timestep   : true ;
	}
}

materials
{
	copper
	{
		builtin : copper ;
		RRR     : 50 ;
	}
}

homology
{
	algorithm : generalized pellikka ;
}

// will be ignored if bfm mesh exists
topology
{

	conductor
	{
		label    : cond 1 ;
		blocks   : 2,4,5,7 ;
		material : copper ;
	}
	air
	{
		label : air ;
		block : 1,3,6,8 ;
	}
}
circuit
{
	number of nodes : 4 ;

	topology
	{

		//RLC Circuit

		voltage source
		{
			label     : Vs ;
			node +    : 0 ;
			node -    : 3 ;
			type      : sine ;
			amplitude : 1 V ;
			frequency : 50 Hz ;
			phase     : 0 deg ;
		}

		terminal pair
		{
			label            : L1 ;
			node +           : 0 ;
			node -           : 1 ;
			input terminals  : [4] ;
			output terminals : [4] ;
		}

		resistor
		{
			label  : R1 ;
			node + : 1 ;
			node - : 2 ;
			value  : 0.0001 Ohm ;
		}

		capacitor
		{
			label  : C1 ;
			node + : 2 ;
			node - : 3 ;
			value  : 128.25 F ;
			order  : 1 ;
		}
	}

	output
	{
		file     : CircuitResults.txt ;
		currents : L1, C1, R1 ;
		voltages : 0,1,2,3 ;
	}
}
boundary conditions
{
}

initial conditions
{
	Temp : 300 K ;
}
