if( USE_HDF5 )
    if ( USE_MPI )
    else()
        message(FATAL_ERROR "Turn on MPI if you want to link against HDF5" )
    endif()
    list( APPEND BELFEM_DEFS "BELFEM_HDF5" )
    set( BELFEM_IO_LIBS "-lhdf5_hl -lhdf5 -lz -ldl ${BELFEM_IO_LIBS}" )
endif()