//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------

mesh
{
	file : 2D_tapestack.msh ;
	unit : m ;
}

solver
{
	linear
	{
		library : strumpack ;
	}

	nonlinear
	{
		tolerance         : 1e-7 ;
		max iterations    : 100 ;
		max relaxation    : 1.0 ;
		target iterations : 50 ;
		algorithm         : Newton ;
		stall tolerance   : 0.001 ;
		watchdog window   : 0 ;
	}

	timestep
	{
		initial timestep       : 0.01 ms ;
		maximum timestep       : 0.2 ms ;
		minimum timestep       : 1 ns ;
		simulation time        : 20 ms ;
		adapt timestep         : true ;
		save every             : 0.2 ms ;
		anderson stabilization : false ;
		scheme                 : bdf5 ;
	}
}


materials
{
	ybco
	{
		builtin          : ybco ;
		file             : sp-ap.hdf5 ;
		resistivity type : power-law ;
	}

	copper
	{
		builtin : copper ;
		RRR     : 50 ;
	}
}

layers : tape
{
	ybco : 1 mum ;
}

homology
{
	algorithm : generalized pellikka ;
}


topology
{
	thinshell : tape
	{
		sidesets : 5:42 ;
	}

	air
	{
		blocks : 1,2,39,40 ;
	}

	conductor
	{
		blocks   : 3:38 ;
		material : copper ;
	}

	curves
	{
		1  : [5,6] ;
		2  : [7,8] ;
		3  : [9,10] ;
		4  : [11,12] ;
		5  : [13,14] ;
		6  : [15,16] ;
		7  : [17,18] ;
		8  : [19,20] ;
		9  : [21,22] ;
		10 : [23,24] ;
		11 : [25,26] ;
		12 : [27,28] ;
		13 : [29,30] ;
		14 : [31,32] ;
		15 : [33,34] ;
		16 : [35,36] ;
		17 : [37,38] ;
		18 : [39,40] ;
		19 : [41,42] ;
	}

}

boundary conditions
{
	current
	{
		input terminals : [3:38] ;
		type            : sine ;
		amplitude       : 3040 A ;
		frequency       : 50 Hz ;
		phase           : 0 ;
	}
}
