add_subdirectory( core )
add_subdirectory( containers )
add_subdirectory( linalg )
add_subdirectory( comm )
add_subdirectory( math )
add_subdirectory( sparse )
add_subdirectory( mesh )
add_subdirectory( homology )
add_subdirectory( circuit )
add_subdirectory( fem )
add_subdirectory( io )
add_subdirectory( ode )
add_subdirectory( physics )
