//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------

mesh
{
	file : disk.msh ;
	unit : mm ;
}

solver
{
	linear
	{
		library : mumps ;
	}

	nonlinear
	{
		tolerance         : 1e-7 ;
		max iterations    : 30 ;
		target iterations : 6 ;
		min relaxation    : 0.01 ;
		algorithm         : Newton ;
	}

	timestep
	{
		initial timestep : 1 ms ;
		minimum timestep : 1 mus ;
		maximum timestep : 5 ms ;
		simulation time  : 500 ms ;
		adapt timestep   : true ;
		save every       : 5 ms ;
		method           : bdf2 ;
	}
}

initial conditions
{
	Temp : 77 K ;
}

materials
{
	ybco
	{
		builtin          : ybco ;
		jc               : 1e8 A/m^2 ;
		n                : 25 ;
		ec               : 1e-4 V/m ;
		resistivity type : power-law ;
	}
}

homology
{
	algorithm : generalized pellikka ;
}

topology
{
	superconductor
	{
		blocks   : 1 ;
		material : ybco ;
	}

	air
	{
		blocks : 2 ;
	}
}

boundary conditions
{
	background : bgfield
	{
		sidesets  : 7:14 ;
		direction : 0, 0, 1 ;
		type      : userdefined ;
		units     : T ;
		file      : src/build/bgpulse.so ;
		label     : BgPulse ;
	}
}
