set( COMPILER_ID 0 )

# try to autodetect compiler if CXX is set
if(DEFINED $ENV{CXX})
    # check compiler exec for hint which compiler we have
    execute_process( COMMAND bash "-c" "if [ $( echo $CXX | grep g++) ]; then echo 1; elif [ $( echo $CXX | grep icpc) ]; then echo 2; elif [ $( echo $CXX | grep pgc++) ]; then echo 3; else echo 0; fi" OUTPUT_VARIABLE COMPILER_ID )
endif()

# if the ID is still 0, try to ask CMake
if( ${COMPILER_ID} EQUAL 0 )
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set( BELFEM_COMPILER "Clang" )
        set( BELFEM_USE_CLANG ON )
        set( BELFEM_USE_INTEL OFF )
        set( COMPILER_ID 1 )
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
        set( BELFEM_COMPILER "AppleClang" )
        set( BELFEM_USE_CLANG ON )
        set( BELFEM_USE_INTEL OFF )
        set( COMPILER_ID 1 )
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set( BELFEM_COMPILER "GNU" )
        set( BELFEM_USE_CLANG OFF )
        set( BELFEM_USE_INTEL OFF )
        set( COMPILER_ID 1 )
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
        set( BELFEM_COMPILER "Intel" )
        set( BELFEM_USE_CLANG OFF )
        set( BELFEM_USE_INTEL ON )
        set( COMPILER_ID 2 )
    else()
        message( FATAL_ERROR, "Unsupported Compiler" )
    endif()
elseif( ${COMPILER_ID} EQUAL 1 AND ${BELFEM_USE_CLANG} EQUAL ON  )
    if( APPLE )
        set( BELFEM_COMPILER "AppleClang" )
    else()
        set( BELFEM_COMPILER "Clang" )
    endif()
    set( BELFEM_USE_INTEL OFF )
elseif( ${COMPILER_ID} EQUAL 1 AND ${BELFEM_USE_CLANG} EQUAL OFF )
    set( BELFEM_COMPILER "GNU" )
    set( BELFEM_USE_INTEL OFF )
elseif( ${COMPILER_ID} EQUAL 2 )
    set( BELFEM_COMPILER "Intel" )
    set( BELFEM_USE_CLANG OFF )
    set( BELFEM_USE_INTEL ON )
endif()

if( ${COMPILER_ID} EQUAL 1 )
    include( ${BELFEM_CONFIG_DIR}/compiler/detect_gcc.cmake )
    include( ${BELFEM_CONFIG_DIR}/compiler/config_gcc.cmake )
elseif( ${COMPILER_ID} EQUAL 2 )
    include( ${BELFEM_CONFIG_DIR}/compiler/detect_icc.cmake )
    include( ${BELFEM_CONFIG_DIR}/compiler/config_icc.cmake )
else()
    message( FATAL_ERROR, "Unsupported Compiler" )
endif()
