//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------

mesh
{
	file : tape.msh ;
	unit : mm ;
}

solver
{
	linear magnetic
	{
		library              : mumps ;
		compute conditioning : true ;
		compression scheme   : off ;
	}

	linear thermal
	{
		library : petsc ;
	}

	nonlinear magnetic
	{
		tolerance         : 1e-7 ;
		max iterations    : 100 ;
		min iterations    : 2 ;
		target iterations : 20 ;
		max relaxation    : 1.0 ;
		min relaxation    : 1e-4 ;
		algorithm         : Newton ;
		tolerance switch  : 1e-4 ;
	}

	nonlinear thermal
	{
		tolerance         : 1e-7 ;
		max iterations    : 50 ;
		min iterations    : 2 ;
		max relaxation    : 1.0 ;
		min relaxation    : 1.0 ;
		target iterations : 20 ;
		tolerance switch  : 1e-4 ;
		coupling          : fully coupled ;
		algorithm         : Newton ;
	}

	timestep
	{
		initial timestep : 0.5 ms ;
		maximum timestep : 1 ms ;
		minimum timestep : 0.001 ms ;
		simulation time  : 0.3 s ;
		adapt timestep   : true ;
		save every       : 1 ms ;
		method           : bdf5 ;
	}
}

materials
{
	rebco
	{
		resistivity type     : riva ;
		critical temperature : 90.0 K ;
		usermat
		{
			file  : src/build/usermat.so ;
			label : hts ;
		}
		defect
		{
			file  : src/build/userdefect.so ;
			label : MyDefect ;
		}
	}
	copper
	{
		usermat
		{
			file  : src/build/usermat.so ;
			label : cu ;
		}
	}

	silver
	{
		usermat
		{
			file  : src/build/usermat.so ;
			label : ag ;
		}
	}

	hastelloy
	{
		usermat
		{
			file  : src/build/usermat.so ;
			label : hast ;
		}
	}

	rint
	{
		usermat
		{
			file  : src/build/usermat.so ;
			label : rint ;
		}
	}

	buffer
	{
		builtin : magnesia ;
	}

}

layers : tape
{
	copper    : 5  mum ;
	silver    : 1.5  mum ;
	hastelloy : 50   mum ;
	buffer    : 0.15 mum ;
	rebco     : 1    mum ;
	rint      : 0.1  mum ;
	silver    : 1    mum ;
	copper    : 5  mum ;
}

homology
{
	algorithm : generalized pellikka ;
}


topology
{
	thinshell : tape
	{
		sideset : 1,2 ;
		//edge coating : on ;
	}
	air
	{
		blocks : 1:2 ;
	}
	curves
	{
		1 : 2 @ 3 ;
		2 : 2 @ 5 ;
	}
}

boundary conditions
{
	current
	{
		input curves  : [ 1 ] ;
		output curves : [ 2 ] ;
		type          : userdefined ;
		units         : A ;
		file          : src/build/userdefect.so ;
		label         : MyCurrent ;
	}
}

initial conditions
{
	Temp : 77 K ;
}
