//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------

mesh
{
	file : helix.msh ;
	unit : mm ;
}

solver
{
	linear
	{
		library : mumps ;
	}

	nonlinear
	{
		tolerance         : 1e-6 ;
		max iterations    : 100 ;
		target iterations : 50 ;
		algorithm         : Picard ;
	}

	timestep
	{
		initial timestep : 0.01 ms ;
		maximum timestep : 0.1 s ;
		simulation time  : 20 s ;
		adapt timestep   : true ;
		//save every       : 0.1 ms ;
	}
}

materials
{

	copper
	{
		builtin : copper ;
		RRR     : 50 ;
	}

}

homology
{
	algorithm : generalized pellikka ;
}


topology
{
	air
	{
		blocks : 5 ;
	}
	conductor
	{
		blocks   : 1:4 ;
		material : copper ;
	}

	periodic
	{
		source : 2,3,4 ;
		target : 294,282,284 ;
	}

}

boundary conditions
{


	current
	{
		input terminals  : 1 ;
		output terminals : 42 ;
		type             : ramp ;
		amplitude        : 1 A ;
		period           : 10 s ;
		offset           : -10 ms ;
	}
}

initial conditions
{
	Temp : 300 K ;
}
