//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------

mesh
{
	file : tapestack3d.msh ;
	unit : mm ;
}

solver
{
	linear
	{
		library : mumps ;
	}

	nonlinear
	{
		tolerance      : 1e-8 ;
		max iterations : 100 ;
		algorithm      : Picard ;
	}

	timestep
	{
		initial timestep : 0.1 ms ;
		maximum timestep : 0.5 ms ;
		simulation time  : 150 ms ;
		adapt timestep   : true ;
	}
}

materials
{
	ybco
	{
		builtin          : ybco ;
		jc               : 1e10 A/m^2 ;
		n                : 20 ;
		ec               : 1e-4 V/m ;
		resistivity type : power-law ;
	}

	copper
	{
		builtin : copper ;
		RRR     : 50 ;
	}

	silver
	{
		builtin : silver ;
		RRR     : 20 ;
	}
	hastelloy
	{
		builtin : hastelloy ;
	}

	buffer
	{
		builtin : magnesia ;
	}
}

layers : tape
{
	copper    : 20 mum ;
	silver    : 2 mum ;
	ybco      : 1.6 mum ;
	buffer    : 0.2 mum ;
	hastelloy : 50 mum ;
	silver    : 1.8 mum ;
	copper    : 20 mum ;
}

homology
{
	algorithm : generalized pellikka ;
}


topology
{
	thinshell : tape
	{
		sideset : 5,6,7,8 ;
	}
	air
	{
		blocks : 1:2 ;
	}
	curves
	{
		1 : 10 @ 5 ;
		2 : 10 @ 6 ;
		3 : 12 @ 5 ;
		4 : 12 @ 6 ;
		5 : 10 @ 7 ;
		6 : 10 @ 8 ;
		7 : 12 @ 7 ;
		8 : 12 @ 8 ;
	}
}

circuit
{
	file : tapestack.cir ;

	topology
	{
		terminal pair
		{
			label         : Z1 ;
			node +        : live ;
			node -        : 0 ;
			input curves  : [1,2] ;
			output curves : [3,4] ;
		}

		terminal pair
		{
			label         : Z2 ;
			node +        : live ;
			node -        : 0 ;
			input curves  : [5,6] ;
			output curves : [7,8] ;
		}
	}

	output
	{
		file     : CircuitResults.txt ;
		currents : Z1, Z2, L1, C1, Is ;
		voltages : live, 0 ;
	}
}

boundary conditions
{
}
