//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------

mesh
{
	file : costheta.msh ;
	unit : mm ;
}

solver
{
	linear
	{
		library : mumps ;
	}

	nonlinear
	{
		tolerance      : 1e-8 ;
		max iterations : 100 ;
		algorithm      : Picard ;
	}

	timestep
	{
		initial timestep : 0.1 s ;
		maximum timestep : 0.5 s ;
		simulation time  : 12 s ;
		adapt timestep   : true ;
	}
}

homology
{
	algorithm : generalized pellikka ;
}

materials
{
	iron
	{
		builtin ;
		bhfile  : bhdata.hdf5 ;
		curve   : RoxieIron ;
	}
}

topology
{

	coil
	{
		blocks : 1:68 ;
	}
	iron
	{
		blocks   : 69:70 ;
		material : iron ;
	}
	air
	{
		blocks : 71:75 ;
	}

	air symmetry
	{
		sidesets : 330, 331, 332 ;
	}

	air antisymmetry
	{
		sidesets : 337, 336, 293, 335, 303, 334 ;
	}
}


boundary conditions
{

	current
	{
		input terminals : 1:68 ;
		type            : ramp ;
		amplitude       : 8498 A ;
		period          : 10 s ;
		offset          : -0.1 s ;
	}
}
