//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------

mesh
{
	file : dipole.msh ;
	unit : mm ;
}

solver
{
	linear
	{
		library : mumps ;
	}

	nonlinear
	{
		tolerance      : 1e-8 ;
		max iterations : 100 ;
		algorithm      : Newton ;
	}

	timestep
	{
		initial timestep : 40 ms ;
		maximum timestep : 40 ms ;
		simulation time  : 2000 ms ;
		adapt timestep   : true ;
	}
}

topology
{
	coil
	{
		blocks : 1,2 ;
	}
	air
	{
		block : 3 ;
	}
}

homology
{
	algorithm : generalized pellikka ;
}

boundary conditions
{
	current
	{
		input terminal : 1 ;
		type           : sine ;
		amplitude      : 1 A ;
		period         : 2 s ;
		offset         : -0.1 s ;
	}

	current
	{
		input terminal : 2 ;
		type           : sine ;
		amplitude      : -1 A ;
		period         : 2 s ;
		offset         : -0.1 s ;
	}
}
