#!/usr/bin/env python3
"""
Wire the markdown documentation into the Doxygen page tree.

Doxygen picks up every ``*.md`` file under ``src/`` and ``doc/`` on its own, but
without help it renders them as one flat alphabetical list of "Related Pages"
under machine-generated URLs such as
``md_src_fem_kernel_doc__r_e_a_d_m_e.html``.  This script supplies the two
things Doxygen needs to build a real navigation tree:

  1. a stable ``{#anchor}`` on the first heading of every page, which fixes the
     generated URL (``fem_kernel_index.html``) and gives ``@ref`` a target;

  2. ``doc/doxygen_nav.dox``, a generated file holding the whole page
     hierarchy as ``@subpage`` directives, including a generated "Example
     decks" page that collects the per-deck READMEs under ``examples/``.

The hierarchy deliberately lives in the ``.dox`` file rather than in the
markdown.  The module READMEs already curate a "Documentation Files" section for
readers browsing the repository on the web, and Doxygen directives written into
those files would show up there as literal ``@subpage`` text.  Keeping the tree
in a ``.dox`` file leaves the markdown clean on both surfaces.

The script is idempotent; re-run it after adding, renaming or removing a
document.

    python3 scripts/update_doc_index.py [--check]

``--check`` reports what would change and exits non-zero instead of writing,
which is what a CI job or a pre-commit hook should call.
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NAV = os.path.join(REPO, "doc", "doxygen_nav.dox")
GROUPS = os.path.join(REPO, "doc", "groups.dox")

BEGIN = "<!-- BEGIN doxygen page tree (generated by scripts/update_doc_index.py) -->"
END = "<!-- END doxygen page tree -->"

# doc/mainpage.md is the Doxygen landing page; it is the one markdown file that
# is allowed to carry @subpage directives, because it exists only for Doxygen.
MAINPAGE = os.path.join(REPO, "doc", "mainpage.md")


# Presentation of the module catalogue on the generated "Module Documentation"
# page. The grouping and the human titles mirror doc/README.md's
# "Module-Specific Documentation" section, which is the same catalogue written
# for someone browsing the repository; the two are meant to stay in step.
#
# Keyed by the module path relative to src/. Every module directory that carries
# a doc/ tree must appear here -- main() raises if one does not, so adding a
# module cannot silently drop it off the page.

# Generated page (doc/doxygen_nav.dox) that carries the example deck READMEs.
DECKS_PAGE = "doc_example_decks"

# Presentation of the repository-level pages on the Doxygen landing page.
#
# The flat alphabetical list this replaced put the AI-process documents second
# and third, ahead of Getting Started, so a first-time reader met the project's
# internal machinery before anything they could use. The three groups below are
# the three reader paths the landing table already names.
#
# Keyed by page anchor. Every page under doc/ and examples/ must appear here --
# main() raises if one does not, so a new document cannot land unfiled. The one
# exception is a deck README (examples/<deck>/README.md next to an input.conf),
# which render_nav() nests under DECKS_PAGE instead.
PAGE_GROUPS = [
    ("Run a simulation", [
        "doc_getting_started",
        "doc_examples",
        DECKS_PAGE,
        "doc_examples_scripts",
        "doc_input_file_reference",
        "doc_parallel_execution",
        "doc_mpi_support",
    ]),
    ("Extend a module", [
        "docmap",
        "doc_index",
        "doc_coding_philosophy",
        "doc_literature_references",
    ]),
    ("Project process", [
        "doc_documentation_guidelines",
        "doc_ai_collaboration_protocol",
        "doc_ai_workflow_best_practices",
    ]),
    ("Code development", [
        "doc_lessons_learned",
        "doc_lessons_learned_evidence",
    ]),
]

MODULE_GROUPS = [
    ("Infrastructure", [
        ("core",       "Core",             "Logging, timing, types, constants and string tools"),
        ("containers", "Containers",       "Cell, Map, Bitset and the other BELFEM container classes"),
        ("linalg",     "Linear Algebra",   "Backend-agnostic linear algebra API and LAPACK wrappers"),
        ("sparse",     "Sparse",           "Sparse storage and the solver interfaces (UMFPACK, MUMPS, STRUMPACK, PARDISO, PETSc)"),
        ("io",         "I/O",              "HDF5, ASCII, CSV, configuration files and XML"),
        ("comm",       "Communication",    "MPI communication abstraction layer"),
        ("mesh",       "Mesh",             "Mesh data structures, I/O (Gmsh, HDF5, Exodus, VTK) and parallel partitioning"),
        ("visualizer", "Visualizer",       "Optional VTK rendering of meshes and curves (USE_VTK, off by default)"),
    ]),
    ("Mathematics", [
        ("math/graph",      "Graph",       "Graph algorithms and partitioning (BFS, DFS, RCM, METIS, SCOTCH)"),
        ("math/tensor",     "Tensor",      "Fourth-order tensor helper"),
        ("math/quaternion", "Quaternion",  "Quaternion value type for 3D rotations"),
        ("numerics/spline", "Spline",      "Spline interpolation"),
        ("numerics/opt",    "Optimizer",   "NLOPT-backed bound-constrained minimisation"),
        ("homology",        "Homology",    "Cohomology algorithms, cut generation and theory"),
    ]),
    ("Finite Elements", [
        ("fem",               "FEM Overview",  "How the finite-element modules fit together"),
        ("fem/kernel",        "FEM Kernel",    "DOF management, hanging nodes, assembly, time stepping and the nonlinear controller"),
        ("fem/interpolation", "Interpolation", "Shape functions, integration points and Nedelec elements"),
        ("fem/iwg",           "IWG",           "Integral weak forms (Poisson, heat conduction, elasticity, time stepping)"),
        ("fem/maxwell",       "Maxwell",       "Electromagnetics: h-phi formulation, thin shells, HTS, cohomology cuts"),
        ("fem/thermal",       "Thermal",       "Transient heat conduction and the magneto-thermal coupling belfem selects for a thermal deck"),
        ("fem/postproc",      "Postprocessing","Mesh-level postprocessing: volumes, surfaces, normals, gradients, mesh checks"),
    ]),
    ("Physics and Circuits", [
        ("physics/materials",  "Materials",   "Material property framework (pure metals, HTS, alloys, user-defined)"),
        ("physics/database",   "Database",    "Precomputed lookup tables on tensor grids"),
        ("physics/gasmodels",  "Gas Models",  "Equation-of-state and transport models"),
        ("physics/gastables",  "Gas Tables",  "Tabulated thermophysical property data"),
        ("circuit",            "Circuit",     "Lumped-element circuit simulator coupled to the FEM problem"),
        ("executables",        "Executables", "belfem and the material, gas and db2exo tools, with their command-line interface"),
    ]),
]

MODULE_TITLES = {rel: (title, blurb)
                 for _, entries in MODULE_GROUPS for rel, title, blurb in entries}


def anchor_for(relpath):
    """Map a repository-relative markdown path onto a Doxygen page label."""
    parts = relpath[: -len(".md")].split(os.sep)

    if parts[0] == "doc":
        prefix, name = ["doc"], parts[-1]
    elif parts[0] == "examples":
        # examples/README.md         -> doc_examples
        # examples/scripts/README.md -> doc_examples_scripts
        # The examples tree has no doc/ subdirectory; the directory name is the
        # page name, so the label reads like the other repository-level pages.
        prefix = ["doc"]
        name = "_".join(parts[:-1] if parts[-1].lower() == "readme" else parts)
    else:  # src/<module path>/doc/<name>
        parts = parts[1:]
        parts.remove("doc")
        prefix, name = parts[:-1], parts[-1]

    if name.lower() == "readme":
        name = "index"

    return re.sub(r"[^a-z0-9_]+", "_", "_".join(prefix + [name]).lower())


def title_of(path):
    """First ATX heading of the file, minus any anchor."""
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("# "):
                return re.sub(r"\s*\{#[^}]*\}\s*$", "", line[2:].strip())
    return os.path.basename(path)


# Markdown that is NOT a documentation page, wherever it appears. These are
# session-bootstrap files for AI collaborators (CLAUDE.md, AGENTS.md), and the
# root copies already sit outside the scanned trees -- so indexing a nested one
# is an accident of where it happens to live, not a decision. It is also a hard
# failure rather than a cosmetic one: every collected page must have a
# PAGE_GROUPS entry, so a generator's own CLAUDE.md dropped into examples/ aborts
# the whole nav build. examples/corc_solder/python/CLAUDE.md did exactly that.
NOT_DOCUMENTATION = {"CLAUDE.md", "AGENTS.md"}

# Directories under examples/ whose markdown is deck-internal rather than a
# manual chapter. A data/ README tells whoever is already editing that deck's
# plugin how to drop a measured table beside it -- it is addressed to someone
# standing in the directory, not to a reader of the Doxygen site, and as a
# top-level page it reads as a stray chapter ("racetrack_usermat plugin data") next to
# Getting Started. Doxyfile.in carries the matching EXCLUDE_PATTERNS entry, so
# the file is not turned into an auto-labelled page either.
NOT_DOCUMENTATION_DIRS = {"data"}


def is_documentation(filename):
    return filename.endswith(".md") and filename not in NOT_DOCUMENTATION


def collect():
    """Return (modules, doc_pages).

    modules is an ordered list of (module path relative to src, doc dir,
    readme filename, [detail filenames]).  doc_pages lists the repository-level
    pages under doc/, excluding README.md and mainpage.md.
    """
    modules = []
    for dirpath, _, filenames in os.walk(os.path.join(REPO, "src")):
        if os.path.basename(dirpath) != "doc":
            continue
        pages = sorted(f for f in filenames if is_documentation(f))
        if not pages:
            continue
        rel = os.path.relpath(os.path.dirname(dirpath), os.path.join(REPO, "src"))
        if "README.md" not in pages:
            sys.stderr.write(
                "warning: src/%s/doc has no README.md; add one so its pages "
                "can be nested\n" % rel
            )
            readme, details = None, pages
        else:
            readme, details = "README.md", [p for p in pages if p != "README.md"]
        modules.append((rel, dirpath, readme, details))
    modules.sort(key=lambda m: m[0])

    doc_dir = os.path.join(REPO, "doc")
    doc_pages = sorted(
        f
        for f in os.listdir(doc_dir)
        if is_documentation(f) and f not in ("README.md", "mainpage.md")
    )
    return modules, doc_pages


def collect_examples():
    """Markdown pages under examples/, repository-relative, README first.

    The example decks are part of the user entry path -- doc/getting_started.md
    points at them -- so they need a stable anchor and a place in the page tree
    like any other reader-facing document.
    """
    root = os.path.join(REPO, "examples")
    if not os.path.isdir(root):
        return []
    found = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in NOT_DOCUMENTATION_DIRS]
        for f in sorted(filenames):
            if is_documentation(f):
                found.append(os.path.join(dirpath, f))
    # examples/README.md is the entry page; keep it at the head of the list.
    top = os.path.join(root, "README.md")
    found.sort(key=lambda q: (q != top, q))
    return found


def is_deck_page(path):
    """True for examples/<deck>/README.md, where <deck> ships an input.conf.

    A deck README is a chapter of the examples manual, not a repository-level
    page: it nests under the generated DECKS_PAGE instead of being filed on
    the landing page. The input.conf beside it is the criterion, so a
    README in examples/scripts/ (no deck) is still filed in PAGE_GROUPS.
    """
    d = os.path.dirname(path)
    return (os.path.basename(path) == "README.md"
            and os.path.dirname(d) == os.path.join(REPO, "examples")
            and os.path.isfile(os.path.join(d, "input.conf")))


def set_anchor(path, anchor, pending):
    """Ensure the file's first ATX heading carries {#anchor}."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()

    if not re.search(r"^#\s+", text, re.M):
        sys.stderr.write(
            "warning: %s has no '# ' heading; no anchor written\n"
            % os.path.relpath(path, REPO)
        )
        return

    # NOTE: the trailing class must not be \s*, which would swallow the newline
    # and the blank line that usually follows the heading.
    new = re.sub(
        r"^#[ \t]+(.+?)(?:[ \t]*\{#[^}]*\})?[ \t]*$",
        lambda m: "# %s {#%s}" % (m.group(1).strip(), anchor),
        text,
        count=1,
        flags=re.M,
    )
    if new != text:
        pending.append((path, new))


def render_nav(modules, doc_pages, anchors, examples):
    """Build the contents of doc/doxygen_nav.dox."""
    by_rel = {rel: (dirpath, readme, details)
              for rel, dirpath, readme, details in modules if readme is not None}

    out = [
        "/*",
        " * Doxygen page hierarchy for the BELFEM markdown documentation.",
        " *",
        " * GENERATED FILE - do not edit by hand.",
        " * Run scripts/update_doc_index.py to regenerate it after adding,",
        " * renaming or removing a document under doc/ or src/<module>/doc/.",
        " */",
        "",
        "/**",
        "@page docmap Module Documentation",
        "",
        "Hand-written documentation for each module: usage guides, algorithm",
        "descriptions and theory notes.  The class, file and namespace indices in",
        "the navigation bar cover the generated API reference separately.",
        "",
    ]

    for group, entries in MODULE_GROUPS:
        listed = [rel for rel, _, _ in entries if rel in by_rel]
        if not listed:
            continue
        out += ["@section docmap_%s %s" % (re.sub(r"[^a-z0-9]+", "_", group.lower()), group), ""]
        for rel, title, blurb in entries:
            if rel not in by_rel:
                continue
            out.append("- @subpage %s &mdash; %s" % (label_for(rel), blurb))
        out.append("")

    out += ["*/", ""]

    for rel, dirpath, readme, details in modules:
        if readme is None:
            continue
        title, _ = MODULE_TITLES[rel]
        out += [
            "/**",
            "@page %s %s" % (label_for(rel), title),
            "",
            "Module source: `src/%s`" % rel,
            "",
            "@subpage %s" % anchors[os.path.join(dirpath, readme)],
        ]
        for name in details:
            out.append("@subpage %s" % anchors[os.path.join(dirpath, name)])
        out += ["*/", ""]

    # The deck READMEs hang off a generated "Example decks" page, the same way a
    # module's pages hang off its mod_* page. (Reopening @page doc_examples here
    # would nest them one level deeper, but Doxygen 1.9 warns about the reused
    # label on every run.)
    out += [
        "/**",
        "@page %s Example decks" % DECKS_PAGE,
        "",
        "One page per shipped deck: what it shows, what it needs, and how to run it.",
        "Meshing, plugins and the shared launcher are covered in the",
        "@ref doc_examples \"examples overview\".",
        "",
    ]
    for q in examples:
        if is_deck_page(q):
            out.append("@subpage %s" % anchors[q])
    out += ["*/", ""]

    return "\n".join(out) + "\n"


def label_for(rel):
    """Doxygen page label for a module directory, e.g. fem/maxwell -> mod_fem_maxwell."""
    return "mod_%s" % re.sub(r"[^a-z0-9_]+", "_", rel.lower())


def render_groups(modules):
    """Build doc/groups.dox, the Doxygen topic tree for the API reference.

    Generated from the same MODULE_GROUPS table as the docmap catalogue, so the
    two views of the module list cannot drift apart. Classes join a group with
    @ingroup in their own documentation block; a group with no members yet still
    renders, carrying its description and the link to the module guide.
    """
    out = [
        "/*",
        " * Doxygen topic (module) tree for the BELFEM API reference.",
        " *",
        " * GENERATED FILE - do not edit by hand.",
        " * Run scripts/update_doc_index.py to regenerate it.",
        " *",
        " * Why it exists: the Classes, Files and Namespaces indices are flat and",
        " * alphabetical. With several hundred headers that is a lookup tool, not a map.",
        " * These groups give the generated reference the same four-bucket shape the",
        " * hand-written catalogue uses, so the two tiers can be read against each other.",
        " */",
        "",
    ]
    documented = {rel for rel, _, readme, _ in modules if readme is not None}
    for group, entries in MODULE_GROUPS:
        gid = re.sub(r"[^a-z0-9]+", "_", group.lower())
        out += ["/**", "@defgroup %s %s" % (gid, group), "",
                "See @ref docmap for the hand-written documentation of these modules.",
                "*/", ""]
        for rel, title, blurb in entries:
            if rel not in documented:
                continue
            anchor = anchor_for(os.path.join("src", rel, "doc", "README.md"))
            out += ["/**",
                    "@defgroup grp_%s %s" % (re.sub(r"[^a-z0-9_]+", "_", rel.lower()), title),
                    "@ingroup %s" % gid, "",
                    blurb + ".", "",
                    "Source: `src/%s`. Hand-written documentation: @ref %s" % (rel, anchor),
                    "*/", ""]
    return "\n".join(out) + "\n"


def render_mainpage_block(doc_pages, anchors, examples):
    """Landing-page contents, grouped by reader path (see PAGE_GROUPS)."""
    lines = [BEGIN, ""]
    for group, entries in PAGE_GROUPS:
        lines += ["### %s" % group, ""]
        for label in entries:
            lines.append("- @subpage %s" % label)
        lines.append("")
    lines += [END]
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    modules, doc_pages = collect()
    pending = []

    # A module that carries documentation but no entry in MODULE_GROUPS would be
    # rendered nowhere on the catalogue page. Fail loudly rather than drop it.
    unclassified = sorted(rel for rel, _, readme, _ in modules
                          if readme is not None and rel not in MODULE_TITLES)
    if unclassified:
        sys.stderr.write(
            "error: no MODULE_GROUPS entry for: %s\n"
            "       add each to scripts/update_doc_index.py (group, title, one-line blurb)\n"
            "       and to the matching section of doc/README.md\n" % ", ".join(unclassified))
        return 1

    filed = {label for _, entries in PAGE_GROUPS for label in entries}

    anchors = {}
    for rel, dirpath, readme, details in modules:
        for name in ([readme] if readme else []) + details:
            path = os.path.join(dirpath, name)
            anchors[path] = anchor_for(os.path.relpath(path, REPO))
            set_anchor(path, anchors[path], pending)

    for name in doc_pages + ["README.md"]:
        path = os.path.join(REPO, "doc", name)
        anchors[path] = anchor_for(os.path.relpath(path, REPO))
        set_anchor(path, anchors[path], pending)

    examples = collect_examples()
    for path in examples:
        anchors[path] = anchor_for(os.path.relpath(path, REPO))
        set_anchor(path, anchors[path], pending)

    duplicates = {}
    for path, label in anchors.items():
        duplicates.setdefault(label, []).append(path)
    for label, paths in sorted(duplicates.items()):
        if len(paths) > 1:
            sys.stderr.write(
                "error: anchor '%s' claimed by %s\n"
                % (label, ", ".join(os.path.relpath(p, REPO) for p in paths))
            )
            return 2

    nav = render_nav(modules, doc_pages, anchors, examples)
    groups = render_groups(modules)
    if not os.path.exists(NAV) or open(NAV, encoding="utf-8").read() != nav:
        pending.append((NAV, nav))

    if not os.path.exists(GROUPS) or open(GROUPS, encoding="utf-8").read() != groups:
        pending.append((GROUPS, groups))

    with open(MAINPAGE, encoding="utf-8") as fh:
        text = fh.read()
    landing = {anchors[os.path.join(REPO, "doc", n)] for n in doc_pages}
    landing |= {anchors[q] for q in examples if not is_deck_page(q)}
    landing |= {"docmap", "doc_index"}
    unfiled = sorted(landing - filed)
    if unfiled:
        sys.stderr.write(
            "error: no PAGE_GROUPS entry for: %s\n"
            "       add each to scripts/update_doc_index.py under the reader path it serves\n"
            % ", ".join(unfiled))
        return 1

    block = render_mainpage_block(doc_pages, anchors, examples)
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    new = (
        pattern.sub(lambda _: block, text)
        if pattern.search(text)
        else text.rstrip("\n") + "\n\n---\n\n" + block + "\n"
    )
    if new != text:
        pending.append((MAINPAGE, new))

    if check:
        for path, _ in pending:
            print("would update:", os.path.relpath(path, REPO))
        print("%d file(s) out of date" % len(pending))
        return 1 if pending else 0

    for path, new in pending:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new)
        print("updated:", os.path.relpath(path, REPO))
    print("%d module(s), %d page(s)" % (len(modules), len(anchors)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
