//---------------------------------------------------------------
// BELFEM INPUTFILE
// Berkeley Lab
//---------------------------------------------------------------
//
// CORC® is a registered trademark of
// Advanced Conductor Technologies LLC, Boulder, CO
//
// The CORC® name is used with kind permission to identify the cable
// technology represented by this example.
//
// https://www.advancedconductor.com/
//

mesh
{
	file : corc.msh ;
	unit : mm ;
}

solver
{
	linear
	{
		library : mumps ;
	}

	nonlinear
	{
		tolerance         : 1e-10 ;
		max iterations    : 100 ;
		target iterations : 50 ;
		algorithm         : Newton ;
	}

	timestep
	{
		initial timestep : 0.001 ms ;
		maximum timestep : 0.1 ms ;
		simulation time  : 20 ms ;
		adapt timestep   : true ;
		save every       : 0.1 ms ;
	}
}


materials
{
	ybco
	{
		builtin          : ybco ;
		jc               : 4e10 A/m^2 ;
		n                : 25 ;
		ec               : 1e-4 V/m ;
		resistivity type : power-law ;
	}
}

layers : tape
{
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
	ybco : 0.1 mum ;
}

homology
{
	algorithm : generalized pellikka ;
}


topology
{
	thinshell : tape
	{
		sidesets : 21, 29, 37 ;
	}

	air
	{
		blocks : 1:2 ;
	}

	curves
	{
		1 : 1 @ 21 ;
		2 : 42 @ 21 ;
		3 : 1 @ 29 ;
		4 : 42 @ 29 ;
		5 : 1 @ 37 ;
		6 : 42 @ 37 ;
	}

	periodic
	{
		source : 2, 3, 4 ;
		target : 116, 118, 123 ;
	}
}

boundary conditions
{
	current
	{
		input curves  : 1,3,5 ;
		output curves : 2,4,6 ;
		type          : sine ;
		amplitude     : 90 A ;
		frequency     : 50 Hz ;
		phase         : 0 deg ;
	}
}
