set( COMPILER_ID 0 )

# use CMAKE_CXX_COMPILER_ID which is set reliably by project()
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set( BELFEM_COMPILER "Clang" )
    set( BELFEM_USE_CLANG ON )
    set( BELFEM_USE_INTEL OFF )
    set( COMPILER_ID 1 )
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    set( BELFEM_COMPILER "AppleClang" )
    set( BELFEM_USE_CLANG ON )
    set( BELFEM_USE_INTEL OFF )
    set( COMPILER_ID 1 )
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set( BELFEM_COMPILER "GNU" )
    set( BELFEM_USE_CLANG OFF )
    set( BELFEM_USE_INTEL OFF )
    set( COMPILER_ID 1 )
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    set( BELFEM_COMPILER "Intel" )
    set( BELFEM_USE_CLANG OFF )
    set( BELFEM_USE_INTEL ON )
    set( COMPILER_ID 2 )
else()
    message( FATAL_ERROR "Unsupported Compiler: ${CMAKE_CXX_COMPILER_ID}" )
endif()

if( ${COMPILER_ID} EQUAL 1 )
    include( ${BELFEM_CONFIG_DIR}/compiler/detect_gcc.cmake )
    include( ${BELFEM_CONFIG_DIR}/compiler/config_gcc.cmake )
elseif( ${COMPILER_ID} EQUAL 2 )
    include( ${BELFEM_CONFIG_DIR}/compiler/detect_icc.cmake )
    include( ${BELFEM_CONFIG_DIR}/compiler/config_icc.cmake )
else()
    message( FATAL_ERROR "Unsupported Compiler: ${CMAKE_CXX_COMPILER_ID}" )
endif()
