# Derive a working Doxygen layout file for the INSTALLED Doxygen, carrying over the
# BELFEM-specific customisations from the checked-in one.
#
# Why: doc/DoxygenLayout.xml is a full layout dump, so it is bound to the Doxygen
# version that produced it. Feeding a newer dump to an older Doxygen makes it reject
# the elements it does not know -- on 1.9.1 the 1.18-shaped file produces
#   error: found unsupported value $SHOW_HEADERFILE for visible attribute in layout file
# plus ~32 warnings for topics/concepts/modules/properties entries. (The error is
# noisy rather than fatal: the custom tabs below still render.)
#
# Rather than pin the checked-in file to one version, regenerate the default layout
# from the installed Doxygen and re-apply only what BELFEM actually customises. That
# delta is small and is READ FROM doc/DoxygenLayout.xml, not hardcoded here, so
# adding a nav tab there flows through without touching this script:
#
#   * every <tab type="user" .../> entry (the Getting Started / Modules /
#     Documentation tabs), re-inserted after the main-page tab
#   * the inheritance/collaboration/directory graph visibilities, which BELFEM
#     forces on rather than leaving to $CLASS_GRAPH / $COLLABORATION_GRAPH
#
# doc/DoxygenLayout.xml is only ever READ. The generated layout lives in the build
# tree, and LAYOUT_FILE in the working Doxyfile is repointed at it -- without that
# last step the generated file would be written and then ignored.
#
# Invoked as: cmake -DDOXYGEN=<exe> -DSOURCE_LAYOUT=<xml> -DWORKING_LAYOUT=<xml>
#                   -DDOXYFILE=<working Doxyfile> -P normalize_doxygen_layout.cmake

if(NOT EXISTS "${SOURCE_LAYOUT}")
    message(FATAL_ERROR "normalize_doxygen_layout: no layout at ${SOURCE_LAYOUT}")
endif()
if(NOT EXISTS "${DOXYFILE}")
    message(FATAL_ERROR "normalize_doxygen_layout: no configuration at ${DOXYFILE}")
endif()

# `doxygen -l` writes the running version's default layout.
execute_process(
    COMMAND "${DOXYGEN}" -l "${WORKING_LAYOUT}"
    RESULT_VARIABLE _rc
    OUTPUT_QUIET
    ERROR_VARIABLE _err)
if(NOT _rc EQUAL 0 OR NOT EXISTS "${WORKING_LAYOUT}")
    message(FATAL_ERROR "normalize_doxygen_layout: 'doxygen -l' failed (${_rc}): ${_err}")
endif()

file(READ "${SOURCE_LAYOUT}" _src)
file(READ "${WORKING_LAYOUT}" _work)

# --- custom navigation tabs ------------------------------------------------------
# Collected with an explicit consume-loop rather than string(REGEX MATCHALL), whose
# result is a CMake LIST: a ';' anywhere in a tab title would be read as a list
# separator and split that tab into two corrupt fragments. Verified behaviour, not a
# theoretical worry -- two tabs go in, three items come out.
set(_tabs "")
set(_count 0)
set(_rest "${_src}")
while(1)
    string(REGEX MATCH "<tab type=\"user\"[^>]*/>" _tab "${_rest}")
    if(NOT _tab)
        break()
    endif()
    string(APPEND _tabs "\n    ${_tab}")
    math(EXPR _count "${_count} + 1")
    string(FIND "${_rest}" "${_tab}" _at)
    string(LENGTH "${_tab}" _len)
    math(EXPR _at "${_at} + ${_len}")
    string(SUBSTRING "${_rest}" ${_at} -1 _rest)
endwhile()

if(_count EQUAL 0)
    # These tabs are the only reason a custom layout file exists at all. Shipping a
    # site whose top bar has silently lost them is worse than not building it.
    message(FATAL_ERROR
        "normalize_doxygen_layout: found no <tab type=\"user\" .../> entries in "
        "${SOURCE_LAYOUT}. Either they were removed, or they are no longer written as "
        "single-line self-closing tags and this script can no longer find them. The "
        "site would lose its custom navigation, so this is fatal rather than a warning.")
endif()

# Insert after the main-page tab. string(REPLACE) is used rather than REGEX REPLACE
# because the replacement text is XML: a backslash in it would be read as a regex
# escape or backreference.
string(REGEX MATCH "<tab type=\"mainpage\"[^>]*/>" _anchor "${_work}")
if(NOT _anchor)
    message(FATAL_ERROR
        "normalize_doxygen_layout: no main-page tab in the layout generated by "
        "'${DOXYGEN} -l'. This script inserts the custom tabs after it; Doxygen has "
        "changed its default layout and the anchor needs updating.")
endif()
string(REPLACE "${_anchor}" "${_anchor}${_tabs}" _work "${_work}")

# Prove the insertion landed. A silently-dropped nav bar is the failure this whole
# script exists to prevent, so it is checked rather than assumed.
string(FIND "${_work}" "<tab type=\"user\"" _inserted)
if(_inserted EQUAL -1)
    message(FATAL_ERROR
        "normalize_doxygen_layout: the ${_count} custom navigation tab(s) were found "
        "but did not survive insertion into the generated layout.")
endif()

# --- graph visibilities BELFEM forces on -----------------------------------------
# Deliberately limited to these three. The checked-in layout also hardcodes
# includegraph / includedbygraph / groupgraph to "yes", which OVERRIDES the Doxyfile:
# INCLUDED_BY_GRAPH is NO on purpose (a 362-node graph on typedefs.hpp), so carrying
# that "yes" over would reinstate the very graphs the Doxyfile switches off. Leaving
# them at the generated default lets $INCLUDED_BY_GRAPH decide, which is what the
# Doxyfile intends.
foreach(_graph inheritancegraph collaborationgraph directorygraph)
    string(REGEX MATCH "<${_graph} visible=\"([^\"]*)\"/>" _found "${_src}")
    if(_found)
        set(_visible "${CMAKE_MATCH_1}")
        string(REGEX MATCH "<${_graph} visible=\"[^\"]*\"/>" _target "${_work}")
        if(_target)
            string(REPLACE "${_target}" "<${_graph} visible=\"${_visible}\"/>" _work "${_work}")
        endif()
    endif()
endforeach()

file(WRITE "${WORKING_LAYOUT}" "${_work}")

# --- make the working configuration actually use it ------------------------------
# After `doxygen -u` the tag still points at the source tree, so the generated layout
# would otherwise be written and never read.
file(READ "${DOXYFILE}" _cfg)
string(REGEX REPLACE "(^|\n)[ \t]*LAYOUT_FILE[ \t]*=[^\n]*"
       "\\1LAYOUT_FILE            = ${WORKING_LAYOUT}" _cfg "${_cfg}")
file(WRITE "${DOXYFILE}" "${_cfg}")

# Without this the generated layout would be written and then never read.
file(READ "${DOXYFILE}" _check)
string(FIND "${_check}" "LAYOUT_FILE            = ${WORKING_LAYOUT}" _at)
if(_at EQUAL -1)
    message(FATAL_ERROR
        "normalize_doxygen_layout: could not repoint LAYOUT_FILE in ${DOXYFILE}. "
        "The generated layout would be ignored and Doxygen would read the "
        "version-bound one from the source tree instead.")
endif()
